# -*- coding: utf-8 -*-
"""polygon_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Byf9T6rXK22cjSRiW2ZZX5HkbrWA3uWT
"""

import matplotlib.pyplot as plt
import numpy as np
from shapely.geometry import Polygon, Point
import matplotlib.patches as patches

# Define the transition width used in the original code
transition_width = 0.3

# Define all the polygons from the original code
polygon_region0 = Polygon([
    (-1, -3.09),  # A
    (-1, 0.3),    # C
    (1.2, 0.3),
    (1.2, -0.3),
    (0.66,-0.3),  # D
    (0.66, -3.09) # B
])

polygon_region3 = Polygon([
    (3.8408, -2.2162),  # A
    (3.5942, -2.1935),  # C
    (3.1053, -1.7821),  # D
    (3.8339, -1.4712)   # B
])

polygon_region4 = Polygon([
    (1.1455, -1.0390),
    (0.8830, -0.8656),
    (0.8239, -2.0134),
    (1.3043, -2.5719),
    (1.7373, -2.7863),
    (2.4617, -2.9485),
    (3.0875, -2.8259),
    (3.2439, -2.1172),
    (2.7218, -2.5038),
    (1.9899, -2.1543),
    (1.6561, -2.0650),
    (1.6256, -1.6862),
    (1.4803, -1.0702)
])

polygon_region5 = Polygon([
            # ( 4.13, -3.06),
            # ( 4.13, -4.56),
            # ( 3.34, -4.56),
            #( 3.19, -4.56),
            ( 2.54, -4.56),
            ( 1.54, -4.56),
            ( 2.05, -4.56),
            ( 1.34, -4.56),
            (-1.14, -4.56),
            (-1.14, -3.06),
            ( 1.34, -3.06),
            ( 1.54, -3.06),
            ( 2.54, -3.06)
            #( 3.19, -3.56),
            # ( 3.34, -3.06),
  #          ( 3.34, -3.26)
])
polygon_region6 = Polygon([
            ( 2.84, -4.56),
            ( 4.13, -4.56),
            ( 4.13, -3.06),
            ( 2.84, -3.06)
        ])
expanded_polygon_region6 = polygon_region6.buffer(transition_width)
# Create expanded versions of each polygon
expanded_polygon_region0 = polygon_region0.buffer(transition_width)
expanded_polygon_region3 = polygon_region3.buffer(transition_width)
expanded_polygon_region4 = polygon_region4.buffer(transition_width)
expanded_polygon_region5 = polygon_region5.buffer(transition_width)

# Set up the figure and axis
plt.figure(figsize=(14, 10))
ax = plt.gca()

# Define a function to plot a polygon and its coordinates
def plot_polygon(polygon, expanded_polygon, name, color, alpha=0.5):
    # Plot the original polygon
    x, y = polygon.exterior.xy
    ax.plot(x, y, color=color, alpha=0.7, linewidth=2, solid_capstyle='round')
    ax.fill(x, y, color=color, alpha=alpha)

    # Plot the expanded polygon
    x_expanded, y_expanded = expanded_polygon.exterior.xy
    ax.plot(x_expanded, y_expanded, color=color, alpha=0.4, linewidth=1, linestyle='--')
    ax.fill(x_expanded, y_expanded, color=color, alpha=alpha*0.4)

    # Label the region
    centroid = polygon.centroid
    ax.text(centroid.x, centroid.y, name, fontsize=12, ha='center', va='center')

    # Plot and label each vertex of the original polygon
    for i, (px, py) in enumerate(zip(x[:-1], y[:-1])):  # Skip the last point as it's the same as the first
        ax.plot(px, py, 'o', color='black', markersize=4)
        ax.text(px+0.05, py+0.05, f'({px:.2f}, {py:.2f})', fontsize=8)

# Plot each polygon with a different color
plot_polygon(polygon_region0, expanded_polygon_region0, "Region 0", "blue", 0.3)
plot_polygon(polygon_region3, expanded_polygon_region3, "Region 3", "green", 0.3)
plot_polygon(polygon_region4, expanded_polygon_region4, "Region 4", "red", 0.3)
plot_polygon(polygon_region5, expanded_polygon_region5, "Region 5", "purple", 0.3)
plot_polygon(polygon_region6, expanded_polygon_region6, "Region 6", "black", 0.3)

# Add special points from the code
P0 = -2.2022
P1 = -1.3268
ax.axhline(y=P0, color='orange', linestyle='-', linewidth=1, alpha=0.7)
ax.text(-1, P0+0.1, f'P0 = {P0}', fontsize=10)
ax.axhline(y=P1, color='orange', linestyle='-', linewidth=1, alpha=0.7)
ax.text(-1, P1+0.1, f'P1 = {P1}', fontsize=10)

ax.axhline(y=-0.9, color='orange', linestyle='-', linewidth=1, alpha=0.7)
ax.text(-1, -0.9+0.1, 'y = -0.9', fontsize=10)

# Set the axis limits to show all polygons with some margin
ax.set_xlim(-2, 5)
ax.set_ylim(-5, 1)

# Important: Invert the y-axis to represent the left-hand coordinate system
ax.invert_yaxis()

# Add coordinate system indicators
plt.arrow(0, 0, 1, 0, head_width=0.1, head_length=0.1, fc='black', ec='black')
plt.arrow(0, 0, 0, -1, head_width=0.1, head_length=0.1, fc='black', ec='black')
plt.text(1.1, 0, 'X', fontsize=12)
plt.text(0, -1.1, 'Y', fontsize=12)
plt.plot(0, 0, 'ko', markersize=5)
plt.text(0.1, 0.1, 'Origin', fontsize=10)

# Set labels and title
ax.set_xlabel('X')
ax.set_ylabel('Y (Inverted for Left-Hand Coordinate System)')
ax.set_title('Compensation Regions with Expanded Transition Zones (Left-Hand Coordinate System)')

# Add a legend for expanded vs. original regions
original_patch = patches.Patch(color='gray', alpha=0.7, label='Original Regions')
expanded_patch = patches.Patch(color='gray', alpha=0.3, label='Expanded Regions (Transition Zones)')
ax.legend(handles=[original_patch, expanded_patch], loc='upper right')

# Add a grid for better readability
ax.grid(True, linestyle='--', alpha=0.3)

# Display the plot
plt.tight_layout()
plt.savefig('compensation_regions_left_hand.png', dpi=300)
plt.show()