# -*- coding: utf-8 -*-
"""laser_tracker_data_process.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12pIR26jem68tdcs3lBTqybxH_O_Otgec
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/fsm/Data
!ls

import numpy as np
from scipy.spatial.transform import Rotation as R
import pandas as pd
import numpy as np

import pandas as pd
import numpy as np

# 读取 CSV 文件
input_file = "tracker_log_0703.csv"
df = pd.read_csv(input_file)

# 重命名列
df.rename(columns={"Distance_2": "d_laser_z", "Distance_3": "d_laser_x"}, inplace=True)

df["d_laser_x"] = df["d_laser_x"]+0.05
df["d_laser_z"] = df["d_laser_z"]+0.05
# 计算修正后的垂直距离
def compute_corrected_distances(laser_x, laser_z, yaw):
    if yaw <0:
      theta = np.radians(yaw + 122)
    else:
      theta = np.radians(yaw - 55)  # 计算偏移角度（转换为弧度）

    # 旋转变换，恢复 30° 方向的真实垂直距离
    d_perp_x = laser_x * np.cos(theta)   # X 方向的修正距离
    d_perp_z = laser_z * np.cos(theta)   # Z 方向的修正距离

    return round(d_perp_x, 3), round(d_perp_z, 3)  # 保留 3 位小数

# 计算修正后的数据
corrected_data = [compute_corrected_distances(lx, lz, yaw)
                  for lx, lz, yaw in zip(df["d_laser_x"], df["d_laser_z"], df["Yaw"])]

# 拆分计算结果
df["laser_x"], df["laser_z"] = zip(*corrected_data)

df["laser_x"] = 4.250-df["laser_x"]
df["laser_z"] = 1.660-df["laser_z"]

# Filter rows based on Yaw value
condition1 = abs(df["Yaw"] - 55) <= 10      # 筛选yaw在55°±10°范围的数据
condition2 = abs(df["Yaw"] - (-123)) <= 10  # 筛选yaw在-123°±10°范围的数据

df = df[condition1 | condition2]

# 仅保留需要的列，并按照要求的顺序排列
df = df[["Timestamp", "d_laser_x", "d_laser_z","laser_x", "laser_z", "X","Y","Z","Yaw", "Roll", "Pitch", ]]
df = df.round(4)  # 所有数值列保留 4 位小数
# 保存修正后的数据为 CSV
output_file = "corrected_tracker_log_0703.csv"
df.to_csv(output_file, index=False, encoding="utf-8")

print(f"修正后的数据已保存至 {output_file}")
print(df.head())  # 显示前几行数据

print(df[df['laser_x'] < 0])